param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$imagesRoot = Join-Path $ProjectRoot "images"
$cameraRoot = Join-Path $imagesRoot "appareil-photo"
$outputFile = Join-Path $ProjectRoot "js/photo-data.js"

$validExtensions = @(".jpg", ".jpeg", ".png", ".webp", ".gif")

$phonePhotos = Get-ChildItem -Path $imagesRoot -File |
    Where-Object { $validExtensions -contains $_.Extension.ToLowerInvariant() } |
    Sort-Object Name |
    ForEach-Object { $_.Name }

$cameraPhotos = Get-ChildItem -Path $cameraRoot -File |
    Where-Object { $validExtensions -contains $_.Extension.ToLowerInvariant() } |
    Sort-Object Name |
    ForEach-Object { $_.Name }

$phoneLines = if ($phonePhotos.Count -gt 0) {
    ($phonePhotos | ForEach-Object { "        `"$($_)`"" }) -join ",`r`n"
} else {
    "        // Ajoute ici tes photos iPhone"
}

$cameraLines = if ($cameraPhotos.Count -gt 0) {
    ($cameraPhotos | ForEach-Object { "        `"$($_)`"" }) -join ",`r`n"
} else {
    "        // Ajoute ici tes photos appareil"
}

$content = @"
// Auto-generated by scripts/sync-photo-data.ps1
window.photoData = {
    phonePhotos: [
$phoneLines
    ],
    cameraPhotos: [
$cameraLines
    ]
};
"@

Set-Content -Path $outputFile -Value $content -Encoding UTF8
Write-Host "photo-data.js mis a jour: $outputFile"
